---
- name: "Create the playbook to create the monitors"
  hosts: localhost
  gather_facts: false

  vars_files:
    - "./dd_monitors.yml"

  tasks:
    - name: "Create the playbook"
      template:
        src: "./datadog_monitors_template.j2"
        dest: "./playbook_dd_monitors.yml"
